# Generated by Django 5.2.17 on 2026-09-18 00:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_identidad_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.CharField(max_length=100)),
                ('lead_consolidado_id', models.CharField(max_length=100)),
                ('fecha_operativa', models.DateField()),
                ('posicion_inicial', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('completada', 'Completada'), ('pendiente', 'Pendiente')], default='asignada', max_length=20)),
                ('ejecucion_id', models.CharField(blank=True, max_length=100)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_diarias', to='cuentas.membresiaempresa')),
            ],
            options={
                'verbose_name': 'asignación diaria',
                'verbose_name_plural': 'asignaciones diarias',
            },
        ),
        migrations.CreateModel(
            name='CapturaEstructurada',
            fields=[
                ('captura_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(max_length=100)),
                ('lead_consolidado_id', models.CharField(blank=True, max_length=100)),
                ('lead_id_origen', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(default='captura_manual', max_length=40)),
                ('declaracion', models.JSONField(default=dict)),
                ('incidencias', models.JSONField(default=list)),
                ('revision_entrada', models.PositiveIntegerField(default=1)),
                ('capturada_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_estructuradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'captura estructurada',
                'verbose_name_plural': 'capturas estructuradas',
            },
        ),
        migrations.CreateModel(
            name='CapturaRevision',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(max_length=100)),
                ('datos_propuestos', models.JSONField(default=dict)),
                ('motivo', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20)),
                ('resolucion', models.CharField(blank=True, max_length=500)),
                ('lead_consolidado_id_resuelto', models.CharField(blank=True, max_length=100)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resolutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capturas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_pendientes_revision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'captura en revisión',
                'verbose_name_plural': 'capturas en revisión',
            },
        ),
        migrations.CreateModel(
            name='EstadoOperativoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.CharField(max_length=100)),
                ('lead_consolidado_id', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('descartado', 'Descartado'), ('perdido', 'Perdido'), ('revision', 'En revisión')], default='abierto', max_length=20)),
                ('proxima_accion_en', models.DateTimeField(blank=True, null=True)),
                ('revision_entrada', models.PositiveIntegerField(default=1)),
                ('priorizacion_vigente_id', models.CharField(blank=True, max_length=100)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('asesor_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_responsables', to='cuentas.membresiaempresa')),
            ],
            options={
                'verbose_name': 'estado operativo de lead',
                'verbose_name_plural': 'estados operativos de leads',
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('evento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(blank=True, max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('tipo_entidad', models.CharField(max_length=80)),
                ('entidad_id', models.CharField(max_length=100)),
                ('correlacion_id', models.UUIDField(blank=True, null=True)),
                ('detalle', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
            },
        ),
        migrations.CreateModel(
            name='GestionComercial',
            fields=[
                ('gestion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(max_length=100)),
                ('lead_consolidado_id', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=40)),
                ('nota', models.CharField(blank=True, max_length=2000)),
                ('proxima_accion_en', models.DateTimeField(blank=True, null=True)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_comerciales', to=settings.AUTH_USER_MODEL)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones', to='crm.asignaciondiaria')),
            ],
            options={
                'verbose_name': 'gestión comercial',
                'verbose_name_plural': 'gestiones comerciales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudIdempotente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.CharField(max_length=100)),
                ('operacion', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=255)),
                ('huella_cuerpo', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('en_proceso', 'En proceso'), ('fallida', 'Fallida')], default='en_proceso', max_length=20)),
                ('respuesta', models.JSONField(default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_idempotentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud idempotente',
                'verbose_name_plural': 'solicitudes idempotentes',
            },
        ),
        migrations.CreateModel(
            name='TrabajoProcesamiento',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('trabajo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(max_length=100)),
                ('tipo_entidad', models.CharField(max_length=40)),
                ('entidad_id', models.CharField(max_length=100)),
                ('tipo_trabajo', models.CharField(max_length=80)),
                ('revision_entrada', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('ejecutando', 'Ejecutando'), ('fallido', 'Fallido'), ('obsoleto', 'Obsoleto'), ('pendiente', 'Pendiente'), ('reintento', 'Reintento')], default='pendiente', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('disponible_en', models.DateTimeField()),
                ('lease_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, max_length=500)),
                ('configuracion', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'trabajo de procesamiento',
                'verbose_name_plural': 'trabajos de procesamiento',
                'indexes': [models.Index(fields=['estado', 'disponible_en'], name='crm_trabajo_estado_disp_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa_id', 'tipo_entidad', 'entidad_id', 'tipo_trabajo', 'revision_entrada'), name='crm_trabajo_logico_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='asignaciondiaria',
            index=models.Index(fields=['asesor', 'fecha_operativa', 'estado'], name='crm_asig_asesor_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignaciondiaria',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'fecha_operativa', 'lead_consolidado_id'), name='crm_asignacion_empresa_fecha_lead_unica'),
        ),
        migrations.AddConstraint(
            model_name='asignaciondiaria',
            constraint=models.UniqueConstraint(fields=('asesor', 'fecha_operativa', 'posicion_inicial'), name='crm_asignacion_asesor_fecha_posicion_unica'),
        ),
        migrations.AddIndex(
            model_name='capturaestructurada',
            index=models.Index(fields=['empresa_id', 'lead_consolidado_id', 'capturada_en'], name='crm_captura_empresa_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='capturarevision',
            index=models.Index(fields=['empresa_id', 'estado', 'creado_en'], name='crm_rev_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='estadooperativolead',
            index=models.Index(fields=['empresa_id', 'estado', 'proxima_accion_en'], name='crm_estado_empresa_accion_idx'),
        ),
        migrations.AddIndex(
            model_name='estadooperativolead',
            index=models.Index(fields=['asesor_responsable', 'estado'], name='crm_estado_asesor_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='estadooperativolead',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'lead_consolidado_id'), name='crm_estado_empresa_lead_unico'),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['empresa_id', 'tipo_entidad', 'entidad_id'], name='crm_audit_empresa_entidad_idx'),
        ),
        migrations.AddIndex(
            model_name='gestioncomercial',
            index=models.Index(fields=['empresa_id', 'lead_consolidado_id', 'registrada_en'], name='crm_gestion_empresa_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudidempotente',
            index=models.Index(fields=['empresa_id', 'estado', 'creada_en'], name='crm_idemp_empresa_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudidempotente',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'actor', 'operacion', 'clave'), name='crm_idempotencia_actor_operacion_unica'),
        ),
    ]
