# Generated by Django 5.2.17 on 2026-09-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_vigencia_y_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoprocesamiento',
            name='resultado_proveedor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
